### PR TITLE
common: default to boot.tmp.cleanOnBoot=true

### PR DESCRIPTION
**Pull request by phaer**
Hello! Just noticed that `boot.tmp.cleanOnBoot` is only enabled on hetzner-cloud machines in srvos. Is there any drawback in doing so on all machines by default or shall we change that? :)

### CODE REVIEW

**Comment by phaer** [comment]
CI is supposedly broken because of https://github.com/numtide/mkdocs-numtide/pull/3

**Comment by zimbatm** [comment]
I'm not sure. @Mic92 do you see any reason not to have this?

**Comment by SuperSandro2000** [comment]
From my personal experience this matches other distros and should be a default in nixos itself actually.

**Comment by Mic92** [comment]
Ok with me

**Comment by zimbatm** [comment]
:+1: 
bors merge

**Pull request merged**
