### PR TITLE
server: only allow normal users to the nix-daemon

### PR DESCRIPTION
**Pull request by zimbatm**
Reduce the attack surface a little bit.

Just an idea I had while talking to @jfroche

### CODE REVIEW

**Comment by zimbatm** [comment]
This probably requires a bunch of fixes to the github action runners and queued-build-hook service

**Comment by SuperSandro2000** [comment]
> This probably requires a bunch of fixes to the github action runners and queued-build-hook service

and harmonia

**Comment by Kranzes** [comment]
I implemented something similar in this commit https://github.com/Kranzes/nix-config/commit/81f7269304bd85dd2f473f9fdc0f00d874c1567f. This didn't break `hercules-ci-agent` because it is set in `trusted-users` which seems to bypass `allowed-users`.

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify rebase

**Comment by zimbatm** [comment]
I think this PR is going to break too many things, not sure if it's worth it.

**Comment by Mic92** [comment]
Let's leave this for projects to set.

**Comment by Kranzes** [comment]
> Let's leave this for projects to set.

At least have the function in the diff be correct :^|

**Pull request closed without merging**
